import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { config } from "@/config";

const argentum = localFont({
  variable: "--font-argentum",
  display: "swap",
  src: [
    {
      path: "./fonts/argentum-sans/ArgentumSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/argentum-sans/ArgentumSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/argentum-sans/ArgentumSans-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
});

const source = localFont({
  variable: "--font-source",
  display: "swap",
  src: [
    {
      path: "./fonts/source-sans-pro/SourceSansPro-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/source-sans-pro/SourceSansPro-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(config.baseUrl),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css"
        />
        <link rel="stylesheet" href="/prism.css" />
      </head>
      <body
        className={`${argentum.variable} ${source.variable} h-full text-gray-900 bg-slate-100 dark:text-stone-50 dark:bg-zinc-800`}
      >
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  );
}
